---
- name: Konfigurasi MikroTik DNS Redirect ke DNS Sehat
  hosts: mikrotik
  gather_facts: no
  tasks:
    - name: Set DNS Server ke DNS Sehat
      community.routeros.command:
        commands:
          - /ip dns set servers=103.58.161.3,103.58.162.3 

    - name: Tambahkan NAT Rule untuk Redirect DNS
      community.routeros.command:
        commands:
          - /ip firewall nat add chain=dstnat protocol=udp dst-port=53 action=redirect to-address=103.58.161.3 to-ports=53 comment="Force DNS" disabled=yes
          - /ip firewall nat add chain=dstnat protocol=tcp dst-port=53 action=redirect to-address=103.58.161.3 to-ports=53 comment="Force DNS" disabled=yes
